[package]
name = "stylus-greeter-l2"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = { version = "0.4.3", features = ["docs"] }
alloy-primitives = "0.3.1"
alloy-sol-types = "0.3.1"
wee_alloc = "0.4.5"
sha3 = "0.10.8"

[features]
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "s"
